// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.


import Foundation

extension Operations.DeprecatedOperationNoCommentsGetRequest: Serializable {
    func serialize(with format: SerializableFormat) throws -> String {
        switch format {
        case .query:
            return try serializeQueryParameterSerializable(self, with: format)
        case .path, .header, .multipart, .form:
            throw SerializationError.invalidSerializationParameter(type: "Operations.DeprecatedOperationNoCommentsGetRequest", format: format.formatDescription)
        }
    }

    @available(*, deprecated)
    func serializeQueryParameters(with format: SerializableFormat) throws -> [QueryParameter] {
        return try serializedQueryParameters(with: nil, formatOverride: format)
    }
}

extension Operations.DeprecatedOperationNoCommentsGetRequest: QueryParameterSerializable {
    @available(*, deprecated)
    func serializedQueryParameters(with parameterDefaults: ParameterDefaults?, formatOverride: SerializableFormat?) throws -> [QueryParameter] {
        let builder = QueryParameterBuilder()
        try builder.addQueryParameters(from: deprecatedParameter, named: "deprecatedParameter", format: formatOverride ?? .query(style: .form, explode: true), parameterDefaults: parameterDefaults)
        return builder.build()
    }
}
