/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * A string based enum
 */
export enum Enum {
    One = "one",
    Two = "two",
    Three = "three",
    FourAndMore = "four_and_more",
}
