"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ErrorType(str, Enum):
    NOT_FOUND = "not_found"
    INVALID = "invalid"
    INTERNAL = "internal"
