# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared

    class SchemeBasicAuth < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :password, String, { 'security': { 'field_name': 'password' } }

      field :username, String, { 'security': { 'field_name': 'username' } }


      sig { params(password: String, username: String).void }
      def initialize(password: nil, username: nil)
        @password = password
        @username = username
      end
    end
  end
end
