// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TextEvent - Represents a single event in a text stream
type TextEvent struct {
	Data string
}

func (o *TextEvent) GetData() string {
	if o == nil {
		return ""
	}
	return o.Data
}
