// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"openapi/v2/pkg/utils"
)

type WeaklyTypedOneOfNullEnumObjectType string

const (
	WeaklyTypedOneOfNullEnumObjectTypeSimpleObject WeaklyTypedOneOfNullEnumObjectType = "simpleObject"
	WeaklyTypedOneOfNullEnumObjectTypeDeepObject   WeaklyTypedOneOfNullEnumObjectType = "deepObject"
)

type WeaklyTypedOneOfNullEnumObject struct {
	SimpleObject *SimpleObject
	DeepObject   *DeepObject

	Type WeaklyTypedOneOfNullEnumObjectType
}

func CreateWeaklyTypedOneOfNullEnumObjectSimpleObject(simpleObject SimpleObject) WeaklyTypedOneOfNullEnumObject {
	typ := WeaklyTypedOneOfNullEnumObjectTypeSimpleObject

	return WeaklyTypedOneOfNullEnumObject{
		SimpleObject: &simpleObject,
		Type:         typ,
	}
}

func CreateWeaklyTypedOneOfNullEnumObjectDeepObject(deepObject DeepObject) WeaklyTypedOneOfNullEnumObject {
	typ := WeaklyTypedOneOfNullEnumObjectTypeDeepObject

	return WeaklyTypedOneOfNullEnumObject{
		DeepObject: &deepObject,
		Type:       typ,
	}
}

func (u *WeaklyTypedOneOfNullEnumObject) UnmarshalJSON(data []byte) error {

	deepObject := DeepObject{}
	if err := utils.UnmarshalJSON(data, &deepObject, "", true, true); err == nil {
		u.DeepObject = &deepObject
		u.Type = WeaklyTypedOneOfNullEnumObjectTypeDeepObject
		return nil
	}

	simpleObject := SimpleObject{}
	if err := utils.UnmarshalJSON(data, &simpleObject, "", true, true); err == nil {
		u.SimpleObject = &simpleObject
		u.Type = WeaklyTypedOneOfNullEnumObjectTypeSimpleObject
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u WeaklyTypedOneOfNullEnumObject) MarshalJSON() ([]byte, error) {
	if u.SimpleObject != nil {
		return utils.MarshalJSON(u.SimpleObject, "", true)
	}

	if u.DeepObject != nil {
		return utils.MarshalJSON(u.DeepObject, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}
