# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class CustomClientPostRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :header_param, ::String, { 'header': { 'field_name': 'headerParam', 'style': 'simple', 'explode': false } }

      field :path_param, ::String, { 'path_param': { 'field_name': 'pathParam', 'style': 'simple', 'explode': false } }

      field :query_string_param, ::String, { 'query_param': { 'field_name': 'queryStringParam', 'style': 'form', 'explode': true } }

      field :simple_object, T.nilable(::OpenApiSDK::Shared::SimpleObject), { 'request': { 'media_type': 'application/json' } }


      sig { params(header_param: ::String, path_param: ::String, query_string_param: ::String, simple_object: T.nilable(::OpenApiSDK::Shared::SimpleObject)).void }
      def initialize(header_param: nil, path_param: nil, query_string_param: nil, simple_object: nil)
        @header_param = header_param
        @path_param = path_param
        @query_string_param = query_string_param
        @simple_object = simple_object
      end
    end
  end
end
