# Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Created
    class FlattenedUnionResponseResponseBodiesResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :message, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('message') } }


      sig { params(message: ::String).void }
      def initialize(message: nil)
        @message = message
      end
    end
  end
end
