<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


class ComplexNumberMaps
{
    /**
     * $bigintMap
     *
     * @var ?array<string, \Brick\Math\BigInteger> $bigintMap
     */
    #[\JMS\Serializer\Annotation\SerializedName('bigintMap')]
    #[\JMS\Serializer\Annotation\Type('array<string, \Brick\Math\BigInteger>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $bigintMap = null;

    /**
     * $bigintStrMap
     *
     * @var ?array<string, \Brick\Math\BigInteger> $bigintStrMap
     */
    #[\JMS\Serializer\Annotation\SerializedName('bigintStrMap')]
    #[\JMS\Serializer\Annotation\Type('array<string, \Brick\Math\BigInteger>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $bigintStrMap = null;

    /**
     * $decimalMap
     *
     * @var ?array<string, \Brick\Math\BigDecimal> $decimalMap
     */
    #[\JMS\Serializer\Annotation\SerializedName('decimalMap')]
    #[\JMS\Serializer\Annotation\Type('array<string, \Brick\Math\BigDecimal>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $decimalMap = null;

    /**
     * $decimalStrMap
     *
     * @var ?array<string, \Brick\Math\BigDecimal> $decimalStrMap
     */
    #[\JMS\Serializer\Annotation\SerializedName('decimalStrMap')]
    #[\JMS\Serializer\Annotation\Type('array<string, \Brick\Math\BigDecimal>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $decimalStrMap = null;

    /**
     * @param  ?array<string, \Brick\Math\BigInteger>  $bigintMap
     * @param  ?array<string, \Brick\Math\BigInteger>  $bigintStrMap
     * @param  ?array<string, \Brick\Math\BigDecimal>  $decimalMap
     * @param  ?array<string, \Brick\Math\BigDecimal>  $decimalStrMap
     */
    public function __construct(?array $bigintMap = null, ?array $bigintStrMap = null, ?array $decimalMap = null, ?array $decimalStrMap = null)
    {
        $this->bigintMap = $bigintMap;
        $this->bigintStrMap = $bigintStrMap;
        $this->decimalMap = $decimalMap;
        $this->decimalStrMap = $decimalStrMap;
    }
}