<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;

use Brick\DateTime\LocalDate;
class DefaultsAndConsts
{
    /**
     *
     * @var int $constBigInt
     */
    #[\JMS\Serializer\Annotation\SerializedName('constBigInt')]
    public int $constBigInt;

    /**
     *
     * @var string $constBigIntStr
     */
    #[\JMS\Serializer\Annotation\SerializedName('constBigIntStr')]
    public string $constBigIntStr;

    /**
     *
     * @var bool $constBool
     */
    #[\JMS\Serializer\Annotation\SerializedName('constBool')]
    public bool $constBool;

    /**
     *
     * @var LocalDate $constDate
     */
    #[\JMS\Serializer\Annotation\SerializedName('constDate')]
    public LocalDate $constDate;

    /**
     *
     * @var \DateTime $constDateTime
     */
    #[\JMS\Serializer\Annotation\SerializedName('constDateTime')]
    public \DateTime $constDateTime;

    /**
     *
     * @var float $constDecimal
     */
    #[\JMS\Serializer\Annotation\SerializedName('constDecimal')]
    public float $constDecimal;

    /**
     *
     * @var string $constDecimalStr
     */
    #[\JMS\Serializer\Annotation\SerializedName('constDecimalStr')]
    public string $constDecimalStr;

    /**
     *
     * @var ConstEnumInt $constEnumInt
     */
    #[\JMS\Serializer\Annotation\SerializedName('constEnumInt')]
    #[\JMS\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Shared\ConstEnumInt')]
    public ConstEnumInt $constEnumInt;

    /**
     *
     * @var ConstEnumStr $constEnumStr
     */
    #[\JMS\Serializer\Annotation\SerializedName('constEnumStr')]
    #[\JMS\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Shared\ConstEnumStr')]
    public ConstEnumStr $constEnumStr;

    /**
     *
     * @var int $constInt
     */
    #[\JMS\Serializer\Annotation\SerializedName('constInt')]
    public int $constInt;

    /**
     *
     * @var float $constNum
     */
    #[\JMS\Serializer\Annotation\SerializedName('constNum')]
    public float $constNum;

    /**
     *
     * @var string $constStr
     */
    #[\JMS\Serializer\Annotation\SerializedName('constStr')]
    public string $constStr;

    /**
     *
     * @var string $constStrDQuotes
     */
    #[\JMS\Serializer\Annotation\SerializedName('constStrDQuotes')]
    public string $constStrDQuotes;

    /**
     *
     * @var string $constStrNull
     */
    #[\JMS\Serializer\Annotation\SerializedName('constStrNull')]
    public string $constStrNull;

    /**
     *
     * @var string $constStrSQuotes
     */
    #[\JMS\Serializer\Annotation\SerializedName('constStrSQuotes')]
    public string $constStrSQuotes;

    /**
     *
     * @var int $defaultBigInt
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultBigInt')]
    public int $defaultBigInt;

    /**
     *
     * @var string $defaultBigIntStr
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultBigIntStr')]
    public string $defaultBigIntStr;

    /**
     *
     * @var bool $defaultBool
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultBool')]
    public bool $defaultBool;

    /**
     *
     * @var LocalDate $defaultDate
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultDate')]
    public LocalDate $defaultDate;

    /**
     *
     * @var \DateTime $defaultDateTime
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultDateTime')]
    public \DateTime $defaultDateTime;

    /**
     *
     * @var float $defaultDecimal
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultDecimal')]
    public float $defaultDecimal;

    /**
     *
     * @var string $defaultDecimalStr
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultDecimalStr')]
    public string $defaultDecimalStr;

    /**
     *
     * @var DefaultEnumInt $defaultEnumInt
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultEnumInt')]
    #[\JMS\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Shared\DefaultEnumInt')]
    public DefaultEnumInt $defaultEnumInt;

    /**
     *
     * @var DefaultEnumStr $defaultEnumStr
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultEnumStr')]
    #[\JMS\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Shared\DefaultEnumStr')]
    public DefaultEnumStr $defaultEnumStr;

    /**
     *
     * @var int $defaultInt
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultInt')]
    public int $defaultInt;

    /**
     *
     * @var float $defaultNum
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultNum')]
    public float $defaultNum;

    /**
     *
     * @var string $defaultStr
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultStr')]
    public string $defaultStr;

    /**
     *
     * @var string $defaultStrDQuotes
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultStrDQuotes')]
    public string $defaultStrDQuotes;

    /**
     *
     * @var string $defaultStrNullable
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultStrNullable')]
    public string $defaultStrNullable;

    /**
     *
     * @var ?string $defaultStrOptional
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultStrOptional')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $defaultStrOptional = null;

    /**
     *
     * @var string $defaultStrSQuotes
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultStrSQuotes')]
    public string $defaultStrSQuotes;

    /**
     *
     * @var string $normalField
     */
    #[\JMS\Serializer\Annotation\SerializedName('normalField')]
    public string $normalField;

    /**
     * @param  ?int  $constBigInt
     * @param  ?string  $constBigIntStr
     * @param  ?bool  $constBool
     * @param  ?LocalDate  $constDate
     * @param  ?\DateTime  $constDateTime
     * @param  ?float  $constDecimal
     * @param  ?string  $constDecimalStr
     * @param  ?ConstEnumInt  $constEnumInt
     * @param  ?ConstEnumStr  $constEnumStr
     * @param  ?int  $constInt
     * @param  ?float  $constNum
     * @param  ?string  $constStr
     * @param  ?string  $constStrDQuotes
     * @param  ?string  $constStrNull
     * @param  ?string  $constStrSQuotes
     * @param  ?int  $defaultBigInt
     * @param  ?string  $defaultBigIntStr
     * @param  ?bool  $defaultBool
     * @param  ?LocalDate  $defaultDate
     * @param  ?\DateTime  $defaultDateTime
     * @param  ?float  $defaultDecimal
     * @param  ?string  $defaultDecimalStr
     * @param  ?DefaultEnumInt  $defaultEnumInt
     * @param  ?DefaultEnumStr  $defaultEnumStr
     * @param  ?int  $defaultInt
     * @param  ?float  $defaultNum
     * @param  ?string  $defaultStr
     * @param  ?string  $defaultStrDQuotes
     * @param  ?string  $defaultStrNullable
     * @param  ?string  $defaultStrSQuotes
     * @param  ?string  $normalField
     * @param  ?string  $defaultStrOptional
     */
    public function __construct(?int $constBigInt = null, ?string $constBigIntStr = null, ?bool $constBool = null, ?LocalDate $constDate = null, ?\DateTime $constDateTime = null, ?float $constDecimal = null, ?string $constDecimalStr = null, ?ConstEnumInt $constEnumInt = null, ?ConstEnumStr $constEnumStr = null, ?int $constInt = null, ?float $constNum = null, ?string $constStr = null, ?string $constStrDQuotes = null, ?string $constStrNull = null, ?string $constStrSQuotes = null, ?int $defaultBigInt = null, ?string $defaultBigIntStr = null, ?bool $defaultBool = null, ?LocalDate $defaultDate = null, ?\DateTime $defaultDateTime = null, ?float $defaultDecimal = null, ?string $defaultDecimalStr = null, ?DefaultEnumInt $defaultEnumInt = null, ?DefaultEnumStr $defaultEnumStr = null, ?int $defaultInt = null, ?float $defaultNum = null, ?string $defaultStr = null, ?string $defaultStrDQuotes = null, ?string $defaultStrNullable = null, ?string $defaultStrSQuotes = null, ?string $normalField = null, ?string $defaultStrOptional = null)
    {
        $this->constBigInt = $constBigInt;
        $this->constBigIntStr = $constBigIntStr;
        $this->constBool = $constBool;
        $this->constDate = $constDate;
        $this->constDateTime = $constDateTime;
        $this->constDecimal = $constDecimal;
        $this->constDecimalStr = $constDecimalStr;
        $this->constEnumInt = $constEnumInt;
        $this->constEnumStr = $constEnumStr;
        $this->constInt = $constInt;
        $this->constNum = $constNum;
        $this->constStr = $constStr;
        $this->constStrDQuotes = $constStrDQuotes;
        $this->constStrNull = $constStrNull;
        $this->constStrSQuotes = $constStrSQuotes;
        $this->defaultBigInt = $defaultBigInt;
        $this->defaultBigIntStr = $defaultBigIntStr;
        $this->defaultBool = $defaultBool;
        $this->defaultDate = $defaultDate;
        $this->defaultDateTime = $defaultDateTime;
        $this->defaultDecimal = $defaultDecimal;
        $this->defaultDecimalStr = $defaultDecimalStr;
        $this->defaultEnumInt = $defaultEnumInt;
        $this->defaultEnumStr = $defaultEnumStr;
        $this->defaultInt = $defaultInt;
        $this->defaultNum = $defaultNum;
        $this->defaultStr = $defaultStr;
        $this->defaultStrDQuotes = $defaultStrDQuotes;
        $this->defaultStrNullable = $defaultStrNullable;
        $this->defaultStrSQuotes = $defaultStrSQuotes;
        $this->normalField = $normalField;
        $this->defaultStrOptional = $defaultStrOptional;
    }
}