<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


class OneOfGenerationStressTest
{
    /**
     *
     * @var mixed $any
     */
    #[\JMS\Serializer\Annotation\SerializedName('any')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $any;

    /**
     *
     * @var mixed $nullableAny
     */
    #[\JMS\Serializer\Annotation\SerializedName('nullableAny')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $nullableAny;

    /**
     *
     * @var string|int $oneOfFromArrayOfTypes
     */
    #[\JMS\Serializer\Annotation\SerializedName('oneOfFromArrayOfTypes')]
    #[\JMS\Serializer\Annotation\Type('string|int')]
    public string|int $oneOfFromArrayOfTypes;

    /**
     *
     * @var string|Two $oneOfSameType
     */
    #[\JMS\Serializer\Annotation\SerializedName('oneOfSameType')]
    #[\JMS\Serializer\Annotation\Type('string|\OpenAPI\OpenAPI\Models\Shared\Two')]
    public string|Two $oneOfSameType;

    /**
     * @param  mixed  $any
     * @param  mixed  $nullableAny
     * @param  string|int|null  $oneOfFromArrayOfTypes
     * @param  string|Two|null  $oneOfSameType
     */
    public function __construct(mixed $any = null, mixed $nullableAny = null, string|int|null $oneOfFromArrayOfTypes = null, string|Two|null $oneOfSameType = null)
    {
        $this->any = $any;
        $this->nullableAny = $nullableAny;
        $this->oneOfFromArrayOfTypes = $oneOfFromArrayOfTypes;
        $this->oneOfSameType = $oneOfSameType;
    }
}