<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


class TypedObject3
{
    /**
     *
     * @var TypedObject3Type $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Shared\TypedObject3Type')]
    public TypedObject3Type $type;

    /**
     *
     * @var string $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * @param  ?TypedObject3Type  $type
     * @param  ?string  $value
     */
    public function __construct(?TypedObject3Type $type = null, ?string $value = null)
    {
        $this->type = $type;
        $this->value = $value;
    }
}