// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var MultipleSimpleSchemeAuthServerList = []string{
	"http://localhost:35456",
}

type MultipleSimpleSchemeAuthSecurity struct {
	APIKeyAuthNew string `security:"scheme,type=apiKey,subtype=header,name=x-api-key"`
	Oauth2        string `security:"scheme,type=oauth2,name=Authorization"`
}

type MultipleSimpleSchemeAuthResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
