// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// RequestBodyPostJSONDataTypesBoolean200ApplicationJSON - OK
type RequestBodyPostJSONDataTypesBoolean200ApplicationJSON struct {
	JSON bool `json:"json"`
}

func (o *RequestBodyPostJSONDataTypesBoolean200ApplicationJSON) GetJSON() bool {
	if o == nil {
		return false
	}
	return o.JSON
}

type RequestBodyPostJSONDataTypesBooleanResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	RequestBodyPostJSONDataTypesBoolean200ApplicationJSONObject *RequestBodyPostJSONDataTypesBoolean200ApplicationJSON
}

func (o *RequestBodyPostJSONDataTypesBooleanResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RequestBodyPostJSONDataTypesBooleanResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RequestBodyPostJSONDataTypesBooleanResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RequestBodyPostJSONDataTypesBooleanResponse) GetRequestBodyPostJSONDataTypesBoolean200ApplicationJSONObject() *RequestBodyPostJSONDataTypesBoolean200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.RequestBodyPostJSONDataTypesBoolean200ApplicationJSONObject
}
