// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/ericlagergren/decimal"
	"net/http"
)

// RequestBodyPostJSONDataTypesDecimalStr200ApplicationJSON - OK
type RequestBodyPostJSONDataTypesDecimalStr200ApplicationJSON struct {
	JSON *decimal.Big `json:"json"`
}

func (o *RequestBodyPostJSONDataTypesDecimalStr200ApplicationJSON) GetJSON() *decimal.Big {
	if o == nil {
		return new(decimal.Big).SetFloat64(0.0)
	}
	return o.JSON
}

type RequestBodyPostJSONDataTypesDecimalStrResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	RequestBodyPostJSONDataTypesDecimalStr200ApplicationJSONObject *RequestBodyPostJSONDataTypesDecimalStr200ApplicationJSON
}

func (o *RequestBodyPostJSONDataTypesDecimalStrResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RequestBodyPostJSONDataTypesDecimalStrResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RequestBodyPostJSONDataTypesDecimalStrResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RequestBodyPostJSONDataTypesDecimalStrResponse) GetRequestBodyPostJSONDataTypesDecimalStr200ApplicationJSONObject() *RequestBodyPostJSONDataTypesDecimalStr200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.RequestBodyPostJSONDataTypesDecimalStr200ApplicationJSONObject
}
