// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

var RequestBodyReadWriteOnlyUnionServerList = []string{
	"http://localhost:35456",
}

type RequestBodyReadWriteOnlyUnionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	WeaklyTypedOneOfReadWriteObject *shared.WeaklyTypedOneOfReadWriteObjectOutput
}

func (o *RequestBodyReadWriteOnlyUnionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RequestBodyReadWriteOnlyUnionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RequestBodyReadWriteOnlyUnionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RequestBodyReadWriteOnlyUnionResponse) GetWeaklyTypedOneOfReadWriteObject() *shared.WeaklyTypedOneOfReadWriteObjectOutput {
	if o == nil {
		return nil
	}
	return o.WeaklyTypedOneOfReadWriteObject
}
