/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type EmptyResponseObjectWithCommentGetResponseBody = {};

/** @internal */
export const EmptyResponseObjectWithCommentGetResponseBody$inboundSchema:
  z.ZodType<
    EmptyResponseObjectWithCommentGetResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type EmptyResponseObjectWithCommentGetResponseBody$Outbound = {};

/** @internal */
export const EmptyResponseObjectWithCommentGetResponseBody$outboundSchema:
  z.ZodType<
    EmptyResponseObjectWithCommentGetResponseBody$Outbound,
    z.ZodTypeDef,
    EmptyResponseObjectWithCommentGetResponseBody
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EmptyResponseObjectWithCommentGetResponseBody$ {
  /** @deprecated use `EmptyResponseObjectWithCommentGetResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    EmptyResponseObjectWithCommentGetResponseBody$inboundSchema;
  /** @deprecated use `EmptyResponseObjectWithCommentGetResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    EmptyResponseObjectWithCommentGetResponseBody$outboundSchema;
  /** @deprecated use `EmptyResponseObjectWithCommentGetResponseBody$Outbound` instead. */
  export type Outbound = EmptyResponseObjectWithCommentGetResponseBody$Outbound;
}

export function emptyResponseObjectWithCommentGetResponseBodyToJSON(
  emptyResponseObjectWithCommentGetResponseBody:
    EmptyResponseObjectWithCommentGetResponseBody,
): string {
  return JSON.stringify(
    EmptyResponseObjectWithCommentGetResponseBody$outboundSchema.parse(
      emptyResponseObjectWithCommentGetResponseBody,
    ),
  );
}

export function emptyResponseObjectWithCommentGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  EmptyResponseObjectWithCommentGetResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EmptyResponseObjectWithCommentGetResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EmptyResponseObjectWithCommentGetResponseBody' from JSON`,
  );
}
