/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * OK
 */
export type RequestBodyPostNotNullableNotRequiredStringBodyResponseBody = {
    data: string;
};

/** @internal */
export const RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$inboundSchema: z.ZodType<
    RequestBodyPostNotNullableNotRequiredStringBodyResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: z.string(),
});

/** @internal */
export type RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$Outbound = {
    data: string;
};

/** @internal */
export const RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$outboundSchema: z.ZodType<
    RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$Outbound,
    z.ZodTypeDef,
    RequestBodyPostNotNullableNotRequiredStringBodyResponseBody
> = z.object({
    data: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$ {
    /** @deprecated use `RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$inboundSchema;
    /** @deprecated use `RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$outboundSchema;
    /** @deprecated use `RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$Outbound` instead. */
    export type Outbound = RequestBodyPostNotNullableNotRequiredStringBodyResponseBody$Outbound;
}
