/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type RequestBodyPostMultipleContentTypesSplitJsonRequestBody = {
    bool: boolean;
    num: number;
    str: string;
};

/**
 * OK
 */
export type RequestBodyPostMultipleContentTypesSplitJsonRes = {
    form?: { [k: string]: any } | undefined;
    json?: { [k: string]: any } | null | undefined;
};

/** @internal */
export namespace RequestBodyPostMultipleContentTypesSplitJsonRequestBody$ {
    export const inboundSchema: z.ZodType<
        RequestBodyPostMultipleContentTypesSplitJsonRequestBody,
        z.ZodTypeDef,
        unknown
    > = z.object({
        bool: z.boolean(),
        num: z.number(),
        str: z.string(),
    });

    export type Outbound = {
        bool: boolean;
        num: number;
        str: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        RequestBodyPostMultipleContentTypesSplitJsonRequestBody
    > = z.object({
        bool: z.boolean(),
        num: z.number(),
        str: z.string(),
    });
}

/** @internal */
export namespace RequestBodyPostMultipleContentTypesSplitJsonRes$ {
    export const inboundSchema: z.ZodType<
        RequestBodyPostMultipleContentTypesSplitJsonRes,
        z.ZodTypeDef,
        unknown
    > = z.object({
        form: z.record(z.any()).optional(),
        json: z.nullable(z.record(z.any())).optional(),
    });

    export type Outbound = {
        form?: { [k: string]: any } | undefined;
        json?: { [k: string]: any } | null | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        RequestBodyPostMultipleContentTypesSplitJsonRes
    > = z.object({
        form: z.record(z.any()).optional(),
        json: z.nullable(z.record(z.any())).optional(),
    });
}
