/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Decimal as Decimal$ } from "../../types";
import * as z from "zod";

/**
 * OK
 */
export type RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody = {
    data: string;
    json: Array<Decimal$ | number>;
};

export type RequestBodyPostJsonDataTypesArrayDecimalStrResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * OK
     */
    object?: RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody | undefined;
};

/** @internal */
export namespace RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody$ {
    export type Inbound = {
        data: string;
        json: Array<string>;
    };

    export const inboundSchema: z.ZodType<
        RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            data: z.string(),
            json: z.array(z.string().transform((v) => new Decimal$(v))),
        })
        .transform((v) => {
            return {
                data: v.data,
                json: v.json,
            };
        });

    export type Outbound = {
        data: string;
        json: Array<string>;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody
    > = z
        .object({
            data: z.string(),
            json: z.array(z.union([z.instanceof(Decimal$), z.number()]).transform((v) => `${v}`)),
        })
        .transform((v) => {
            return {
                data: v.data,
                json: v.json,
            };
        });
}

/** @internal */
export namespace RequestBodyPostJsonDataTypesArrayDecimalStrResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        RequestBodyPostJsonDataTypesArrayDecimalStrResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z
                .lazy(() => RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody$.inboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        RequestBodyPostJsonDataTypesArrayDecimalStrResponse
    > = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z
                .lazy(() => RequestBodyPostJsonDataTypesArrayDecimalStrResponseBody$.outboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
