/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import * as z from "zod";

/**
 * OK
 */
export type TypedObjectNullableOneOfPostRes = {
    json: shared.TypedObjectNullableOneOf | null;
};

export type TypedObjectNullableOneOfPostResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * OK
     */
    res?: TypedObjectNullableOneOfPostRes | undefined;
};

/** @internal */
export namespace TypedObjectNullableOneOfPostRes$ {
    export type Inbound = {
        json: shared.TypedObjectNullableOneOf$.Inbound | null;
    };

    export const inboundSchema: z.ZodType<TypedObjectNullableOneOfPostRes, z.ZodTypeDef, Inbound> =
        z
            .object({
                json: z.nullable(shared.TypedObjectNullableOneOf$.inboundSchema),
            })
            .transform((v) => {
                return {
                    json: v.json,
                };
            });

    export type Outbound = {
        json: shared.TypedObjectNullableOneOf$.Outbound | null;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        TypedObjectNullableOneOfPostRes
    > = z
        .object({
            json: z.nullable(shared.TypedObjectNullableOneOf$.outboundSchema),
        })
        .transform((v) => {
            return {
                json: v.json,
            };
        });
}

/** @internal */
export namespace TypedObjectNullableOneOfPostResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        res?: TypedObjectNullableOneOfPostRes$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        TypedObjectNullableOneOfPostResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            res: z.lazy(() => TypedObjectNullableOneOfPostRes$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.res === undefined ? null : { res: v.res }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        res?: TypedObjectNullableOneOfPostRes$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        TypedObjectNullableOneOfPostResponse
    > = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            res: z.lazy(() => TypedObjectNullableOneOfPostRes$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.res === undefined ? null : { res: v.res }),
            };
        });
}
