<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use OpenAPI\OpenAPI\Models\Shared;
/** ArrayOfDiscriminatedUnionsRes - OK */
class ArrayOfDiscriminatedUnionsRes
{
    /**
     * $json
     *
     * @var array<Shared\SimpleObjectWithType|Shared\DeepObjectWithType> $json
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('json')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\OpenAPI\OpenAPI\Models\Shared\SimpleObjectWithType|\OpenAPI\OpenAPI\Models\Shared\DeepObjectWithType>')]
    public array $json;

    /**
     * @param  array<Shared\SimpleObjectWithType|Shared\DeepObjectWithType>  $json
     */
    public function __construct(array $json)
    {
        $this->json = $json;
    }
}