<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use OpenAPI\OpenAPI\Models\Shared;
/** ComponentBodyAndParamConflictRes - OK */
class ComponentBodyAndParamConflictRes
{
    /**
     * $args
     *
     * @var array<string, string> $args
     */
    #[\JMS\Serializer\Annotation\SerializedName('args')]
    #[\JMS\Serializer\Annotation\Type('array<string, string>')]
    public array $args;

    /**
     * A simple object that uses all our supported primitive types and enums and has optional properties.
     *
     * @var Shared\SimpleObject $json
     */
    #[\JMS\Serializer\Annotation\SerializedName('json')]
    #[\JMS\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Shared\SimpleObject')]
    public Shared\SimpleObject $json;

    /**
     * @param  ?array<string, string>  $args
     * @param  ?Shared\SimpleObject  $json
     */
    public function __construct(?array $args = null, ?Shared\SimpleObject $json = null)
    {
        $this->args = $args;
        $this->json = $json;
    }
}