<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class FlattenedEnvelopePaginationResponseRequest
{
    /**
     * The page token used to request a specific page of the search results
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     * @param  ?string  $cursor
     */
    public function __construct(?string $cursor = null)
    {
        $this->cursor = $cursor;
    }
}