<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


/** HeaderParamsObjectRes - OK */
class HeaderParamsObjectRes
{
    #[\JMS\Serializer\Annotation\SerializedName('headers')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Operations\HeaderParamsObjectHeaders')]
    public HeaderParamsObjectHeaders $headers;

    public function __construct()
    {
        $this->headers = new \OpenAPI\OpenAPI\Models\Operations\HeaderParamsObjectHeaders();
    }
}