<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


class JsonQueryParamsObjectSmallerArgs
{
    #[\JMS\Serializer\Annotation\SerializedName('deepObjParam')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $deepObjParam;

    #[\JMS\Serializer\Annotation\SerializedName('simpleObjParam')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $simpleObjParam;

    public function __construct()
    {
        $this->deepObjParam = '';
        $this->simpleObjParam = '';
    }
}