<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use OpenAPI\OpenAPI\Models\Shared;
/** NullableOneOfTypeInObjectPostRes - OK */
class NullableOneOfTypeInObjectPostRes
{
    /**
     *
     * @var Shared\NullableOneOfTypeInObject $json
     */
    #[\JMS\Serializer\Annotation\SerializedName('json')]
    #[\JMS\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Shared\NullableOneOfTypeInObject')]
    public Shared\NullableOneOfTypeInObject $json;

    /**
     * @param  ?Shared\NullableOneOfTypeInObject  $json
     */
    public function __construct(?Shared\NullableOneOfTypeInObject $json = null)
    {
        $this->json = $json;
    }
}