/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.models.shared.NullableObject;
import org.openapis.openapi.models.shared.NullableOptionalObject;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class NullableRequiredSharedObjectPostRequestBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("NullableOptionalObj")
    private JsonNullable<? extends NullableOptionalObject> nullableOptionalObj;

    @JsonInclude(Include.ALWAYS)
    @JsonProperty("NullableRequiredObj")
    private Optional<? extends NullableObject> nullableRequiredObj;

    @JsonCreator
    public NullableRequiredSharedObjectPostRequestBody(
            @JsonProperty("NullableOptionalObj") JsonNullable<? extends NullableOptionalObject> nullableOptionalObj,
            @JsonProperty("NullableRequiredObj") Optional<? extends NullableObject> nullableRequiredObj) {
        Utils.checkNotNull(nullableOptionalObj, "nullableOptionalObj");
        Utils.checkNotNull(nullableRequiredObj, "nullableRequiredObj");
        this.nullableOptionalObj = nullableOptionalObj;
        this.nullableRequiredObj = nullableRequiredObj;
    }
    
    public NullableRequiredSharedObjectPostRequestBody() {
        this(JsonNullable.undefined(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<NullableOptionalObject> nullableOptionalObj() {
        return (JsonNullable<NullableOptionalObject>) nullableOptionalObj;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<NullableObject> nullableRequiredObj() {
        return (Optional<NullableObject>) nullableRequiredObj;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public NullableRequiredSharedObjectPostRequestBody withNullableOptionalObj(NullableOptionalObject nullableOptionalObj) {
        Utils.checkNotNull(nullableOptionalObj, "nullableOptionalObj");
        this.nullableOptionalObj = JsonNullable.of(nullableOptionalObj);
        return this;
    }

    public NullableRequiredSharedObjectPostRequestBody withNullableOptionalObj(JsonNullable<? extends NullableOptionalObject> nullableOptionalObj) {
        Utils.checkNotNull(nullableOptionalObj, "nullableOptionalObj");
        this.nullableOptionalObj = nullableOptionalObj;
        return this;
    }

    public NullableRequiredSharedObjectPostRequestBody withNullableRequiredObj(NullableObject nullableRequiredObj) {
        Utils.checkNotNull(nullableRequiredObj, "nullableRequiredObj");
        this.nullableRequiredObj = Optional.ofNullable(nullableRequiredObj);
        return this;
    }

    public NullableRequiredSharedObjectPostRequestBody withNullableRequiredObj(Optional<? extends NullableObject> nullableRequiredObj) {
        Utils.checkNotNull(nullableRequiredObj, "nullableRequiredObj");
        this.nullableRequiredObj = nullableRequiredObj;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NullableRequiredSharedObjectPostRequestBody other = (NullableRequiredSharedObjectPostRequestBody) o;
        return 
            Objects.deepEquals(this.nullableOptionalObj, other.nullableOptionalObj) &&
            Objects.deepEquals(this.nullableRequiredObj, other.nullableRequiredObj);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            nullableOptionalObj,
            nullableRequiredObj);
    }
    
    @Override
    public String toString() {
        return Utils.toString(NullableRequiredSharedObjectPostRequestBody.class,
                "nullableOptionalObj", nullableOptionalObj,
                "nullableRequiredObj", nullableRequiredObj);
    }
    
    public final static class Builder {
 
        private JsonNullable<? extends NullableOptionalObject> nullableOptionalObj = JsonNullable.undefined();
 
        private Optional<? extends NullableObject> nullableRequiredObj = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder nullableOptionalObj(NullableOptionalObject nullableOptionalObj) {
            Utils.checkNotNull(nullableOptionalObj, "nullableOptionalObj");
            this.nullableOptionalObj = JsonNullable.of(nullableOptionalObj);
            return this;
        }

        public Builder nullableOptionalObj(JsonNullable<? extends NullableOptionalObject> nullableOptionalObj) {
            Utils.checkNotNull(nullableOptionalObj, "nullableOptionalObj");
            this.nullableOptionalObj = nullableOptionalObj;
            return this;
        }

        public Builder nullableRequiredObj(NullableObject nullableRequiredObj) {
            Utils.checkNotNull(nullableRequiredObj, "nullableRequiredObj");
            this.nullableRequiredObj = Optional.ofNullable(nullableRequiredObj);
            return this;
        }

        public Builder nullableRequiredObj(Optional<? extends NullableObject> nullableRequiredObj) {
            Utils.checkNotNull(nullableRequiredObj, "nullableRequiredObj");
            this.nullableRequiredObj = nullableRequiredObj;
            return this;
        }
        
        public NullableRequiredSharedObjectPostRequestBody build() {
            return new NullableRequiredSharedObjectPostRequestBody(
                nullableOptionalObj,
                nullableRequiredObj);
        }
    }
}

