/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapis.openapi.models.errors.SDKError;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class Oauth2AuthRequestBuilder {

    private Oauth2AuthSecurity security;
    private final SDKMethodInterfaces.MethodCallOauth2Auth sdk;

    public Oauth2AuthRequestBuilder(SDKMethodInterfaces.MethodCallOauth2Auth sdk) {
        this.sdk = sdk;
    }

    public Oauth2AuthRequestBuilder security(Oauth2AuthSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public Oauth2AuthResponse call() throws Exception {

        return sdk.oauth2Auth(
            security);
    }
}
