/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.models.shared.MapObjValueCamelCase;
import org.openapis.openapi.utils.Response;
import org.openapis.openapi.utils.Utils;


public class RequestBodyPostApplicationJsonMapObjCamelCaseResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * OK
     */
    private Optional<? extends MapObjValueCamelCase> mapObjValueCamelCase;

    @JsonCreator
    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends MapObjValueCamelCase> mapObjValueCamelCase) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(mapObjValueCamelCase, "mapObjValueCamelCase");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.mapObjValueCamelCase = mapObjValueCamelCase;
    }
    
    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<MapObjValueCamelCase> mapObjValueCamelCase() {
        return (Optional<MapObjValueCamelCase>) mapObjValueCamelCase;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withMapObjValueCamelCase(MapObjValueCamelCase mapObjValueCamelCase) {
        Utils.checkNotNull(mapObjValueCamelCase, "mapObjValueCamelCase");
        this.mapObjValueCamelCase = Optional.ofNullable(mapObjValueCamelCase);
        return this;
    }

    /**
     * OK
     */
    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withMapObjValueCamelCase(Optional<? extends MapObjValueCamelCase> mapObjValueCamelCase) {
        Utils.checkNotNull(mapObjValueCamelCase, "mapObjValueCamelCase");
        this.mapObjValueCamelCase = mapObjValueCamelCase;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RequestBodyPostApplicationJsonMapObjCamelCaseResponse other = (RequestBodyPostApplicationJsonMapObjCamelCaseResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.mapObjValueCamelCase, other.mapObjValueCamelCase);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            mapObjValueCamelCase);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RequestBodyPostApplicationJsonMapObjCamelCaseResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "mapObjValueCamelCase", mapObjValueCamelCase);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends MapObjValueCamelCase> mapObjValueCamelCase = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * OK
         */
        public Builder mapObjValueCamelCase(MapObjValueCamelCase mapObjValueCamelCase) {
            Utils.checkNotNull(mapObjValueCamelCase, "mapObjValueCamelCase");
            this.mapObjValueCamelCase = Optional.ofNullable(mapObjValueCamelCase);
            return this;
        }

        /**
         * OK
         */
        public Builder mapObjValueCamelCase(Optional<? extends MapObjValueCamelCase> mapObjValueCamelCase) {
            Utils.checkNotNull(mapObjValueCamelCase, "mapObjValueCamelCase");
            this.mapObjValueCamelCase = mapObjValueCamelCase;
            return this;
        }
        
        public RequestBodyPostApplicationJsonMapObjCamelCaseResponse build() {
            return new RequestBodyPostApplicationJsonMapObjCamelCaseResponse(
                contentType,
                statusCode,
                rawResponse,
                mapObjValueCamelCase);
        }
    }
}

