/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.openapis.openapi.models.shared.SimpleObject;
import org.openapis.openapi.utils.Utils;

public class RequestBodyPostApplicationJsonArrayOfMapRequestBuilder {

    private List<Map<String, SimpleObject>> request;
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallRequestBodyPostApplicationJsonArrayOfMap sdk;

    public RequestBodyPostApplicationJsonArrayOfMapRequestBuilder(SDKMethodInterfaces.MethodCallRequestBodyPostApplicationJsonArrayOfMap sdk) {
        this.sdk = sdk;
    }

    public RequestBodyPostApplicationJsonArrayOfMapRequestBuilder request(List<Map<String, SimpleObject>> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public RequestBodyPostApplicationJsonArrayOfMapRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public RequestBodyPostApplicationJsonArrayOfMapRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public RequestBodyPostApplicationJsonArrayOfMapResponse call() throws Exception {

        return sdk.requestBodyPostApplicationJsonArrayOfMap(
            request,
            serverURL);
    }
}
