"""Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.models.shared import jsonevent as shared_jsonevent
from openapi.types import BaseModel
from pydantic import SkipValidation
from typing import AsyncGenerator, Dict, Generator, List, TypedDict, Union

JSON__SERVERS = [
	"http://localhost:35456",
]


class JSONResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: Union[Generator[shared_jsonevent.JSONEventTypedDict, None, None], AsyncGenerator[shared_jsonevent.JSONEventTypedDict, None]]
    

class JSONResponse(BaseModel):
    headers: Dict[str, List[str]]
    result: SkipValidation[Union[Generator[shared_jsonevent.JSONEvent, None, None], AsyncGenerator[shared_jsonevent.JSONEvent, None]]]
    
