"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from sdk import utils
from typing import Optional

class NullableRequiredPropertyPostRequestBodyNullableRequiredEnum(str, Enum):
    FIRST = 'first'
    SECOND = 'second'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class NullableRequiredPropertyPostRequestBody:
    nullable_required_array: list[float] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('NullableRequiredArray') }})
    nullable_required_enum: NullableRequiredPropertyPostRequestBodyNullableRequiredEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('NullableRequiredEnum') }})
    nullable_required_int: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('NullableRequiredInt') }})
    nullable_optional_int: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('NullableOptionalInt'), 'exclude': lambda f: f is None }})
    




@dataclasses.dataclass
class NullableRequiredPropertyPostResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    nullable_required_property_post_200_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

