"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from enum import Enum

UNION_ERRORS_DISCRIMINATED_GET_SERVERS = [
	"http://localhost:35456",
]


class ErrorTag(str, Enum):
    TAG1 = 'tag1'
    TAG2 = 'tag2'


@dataclasses.dataclass
class UnionErrorsDiscriminatedGetRequest:
    error_tag: ErrorTag = dataclasses.field(metadata={'query_param': { 'field_name': 'errorTag', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class UnionErrorsDiscriminatedGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    

