// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum AuthorizationHeaderModificationResponse {
        case empty
        case token(Operations.AuthorizationHeaderModificationToken)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func token() throws -> Operations.AuthorizationHeaderModificationToken {
            guard case .token(let value) = self else {
                throw OpenAPIError.missingResponseData
            }
            return value
        }
    }
}
