// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// OK
    public struct RequestBodyPutBytesWithParamsRes {
        public let args: Operations.RequestBodyPutBytesWithParamsResArgs
        public let data: String

        /// Creates an object with the specified parameters
        ///
        ///
        public init(args: Operations.RequestBodyPutBytesWithParamsResArgs, data: String) {
            self.args = args
            self.data = data
        }
    }
}

extension Operations.RequestBodyPutBytesWithParamsRes: Codable {
    enum CodingKeys: String, CodingKey {
        case args
        case data
    }
}

