// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// OK
    public struct RequestBodyPostEmptyBodyRetainedWithAllOptionalFieldsResponseBody {
        public let json: Operations.RequestBodyPostEmptyBodyRetainedWithAllOptionalFieldsJson

        /// Creates an object with the specified parameters
        ///
        ///
        public init(json: Operations.RequestBodyPostEmptyBodyRetainedWithAllOptionalFieldsJson) {
            self.json = json
        }
    }}

extension Operations.RequestBodyPostEmptyBodyRetainedWithAllOptionalFieldsResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case json
    }
}

