// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct RequestBodyPostEmptyObjectRequestBodyEmpty {

        /// Creates an object
        ///
        ///
        public init() {
        }
    }
}

extension Operations.RequestBodyPostEmptyObjectRequestBodyEmpty: Codable {
}

