/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;


public class MixedParametersCamelCaseRequest {
    @SpeakeasyMetadata("header:style=simple,explode=false,name=header_param")
    public String headerParam;

    public MixedParametersCamelCaseRequest withHeaderParam(String headerParam) {
        this.headerParam = headerParam;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=path_param")
    public String pathParam;

    public MixedParametersCamelCaseRequest withPathParam(String pathParam) {
        this.pathParam = pathParam;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=query_string_param")
    public String queryStringParam;

    public MixedParametersCamelCaseRequest withQueryStringParam(String queryStringParam) {
        this.queryStringParam = queryStringParam;
        return this;
    }
    
    public MixedParametersCamelCaseRequest(@JsonProperty("header_param") String headerParam, @JsonProperty("path_param") String pathParam, @JsonProperty("query_string_param") String queryStringParam) {
        this.headerParam = headerParam;
        this.pathParam = pathParam;
        this.queryStringParam = queryStringParam;
  }
}
