/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NullableTypedObjectPostRes - OK
 */

public class NullableTypedObjectPostRes {
    @JsonProperty("json")
    public org.openapis.openapi.models.shared.TypedObject1 json;

    public NullableTypedObjectPostRes withJson(org.openapis.openapi.models.shared.TypedObject1 json) {
        this.json = json;
        return this;
    }
    
    public NullableTypedObjectPostRes(@JsonProperty("json") org.openapis.openapi.models.shared.TypedObject1 json) {
        this.json = json;
  }
}
