/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class RequestBodyPostJsonDataTypesNumberResponse {
    
    public String contentType;

    public RequestBodyPostJsonDataTypesNumberResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public RequestBodyPostJsonDataTypesNumberResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public RequestBodyPostJsonDataTypesNumberResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public RequestBodyPostJSONDataTypesNumber200ApplicationJSON requestBodyPostJSONDataTypesNumber200ApplicationJSONObject;

    public RequestBodyPostJsonDataTypesNumberResponse withRequestBodyPostJSONDataTypesNumber200ApplicationJSONObject(RequestBodyPostJSONDataTypesNumber200ApplicationJSON requestBodyPostJSONDataTypesNumber200ApplicationJSONObject) {
        this.requestBodyPostJSONDataTypesNumber200ApplicationJSONObject = requestBodyPostJSONDataTypesNumber200ApplicationJSONObject;
        return this;
    }
    
    public RequestBodyPostJsonDataTypesNumberResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
