/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class RequestBodyPostApplicationJsonMapObjCamelCaseResponse {
    
    public String contentType;

    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public org.openapis.openapi.models.shared.MapObjValueCamelCase mapObjValueCamelCase;

    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse withMapObjValueCamelCase(org.openapis.openapi.models.shared.MapObjValueCamelCase mapObjValueCamelCase) {
        this.mapObjValueCamelCase = mapObjValueCamelCase;
        return this;
    }
    
    public RequestBodyPostApplicationJsonMapObjCamelCaseResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
