/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class RequestBodyPostNotNullableNotRequiredStringBodyResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public RequestBodyPostNotNullableNotRequiredStringBodyResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public RequestBodyPostNotNullableNotRequiredStringBodyResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public RequestBodyPostNotNullableNotRequiredStringBodyResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public RequestBodyPostNotNullableNotRequiredStringBody200ApplicationJSON requestBodyPostNotNullableNotRequiredStringBody200ApplicationJSONObject;

    public RequestBodyPostNotNullableNotRequiredStringBodyResponse withRequestBodyPostNotNullableNotRequiredStringBody200ApplicationJSONObject(RequestBodyPostNotNullableNotRequiredStringBody200ApplicationJSON requestBodyPostNotNullableNotRequiredStringBody200ApplicationJSONObject) {
        this.requestBodyPostNotNullableNotRequiredStringBody200ApplicationJSONObject = requestBodyPostNotNullableNotRequiredStringBody200ApplicationJSONObject;
        return this;
    }
    
    public RequestBodyPostNotNullableNotRequiredStringBodyResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
