/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;


public class CommonHelpers {
    public static void recordTest(String id) throws Exception {
        Files.writeString(Paths.get("test-java-record.txt"), id + "\n", StandardOpenOption.CREATE,
                StandardOpenOption.APPEND);
    }
}