// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

// Error - Internal Server Error
type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	if e.Message == nil {
		return "unknown error"
	}

	return *e.Message
}
