# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/validcircularreferenceobject'

module OpenApiSDK
  module Operations

    class CircularReferenceGetResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # HTTP response status code for this operation
      field :status_code, Integer
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, T.nilable(Faraday::Response)
      # OK
      field :valid_circular_reference_object, T.nilable(Shared::ValidCircularReferenceObject)


      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), valid_circular_reference_object: T.nilable(Shared::ValidCircularReferenceObject)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, valid_circular_reference_object: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @valid_circular_reference_object = valid_circular_reference_object
      end
    end
  end
end
