# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Operations
    OPEN_ID_CONNECT_AUTH_NEW_SERVERS = [
      'http://localhost:35456'
    ].freeze

    class OpenIdConnectAuthNewSecurity < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :open_id_connect, String, { 'security': { 'scheme': true, 'type': 'openIdConnect', 'field_name': 'Authorization' } }


      sig { params(open_id_connect: String).void }
      def initialize(open_id_connect: nil)
        @open_id_connect = open_id_connect
      end
    end


    class OpenIdConnectAuthNewResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :content_type, String

      field :status_code, Integer

      field :raw_response, T.nilable(Faraday::Response)


      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
      end
    end
  end
end
