# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Operations

    class OpenIdConnectAuthSecurity < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :open_id_connect, String, { 'security': { 'scheme': true, 'type': 'openIdConnect', 'field_name': 'Authorization' } }


      sig { params(open_id_connect: String).void }
      def initialize(open_id_connect: nil)
        @open_id_connect = open_id_connect
      end
    end

    # Successful authentication.
    class OpenIdConnectAuthToken < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :authenticated, T::Boolean, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('authenticated') } }

      field :token, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('token') } }


      sig { params(authenticated: T::Boolean, token: String).void }
      def initialize(authenticated: nil, token: nil)
        @authenticated = authenticated
        @token = token
      end
    end


    class OpenIdConnectAuthResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :content_type, String

      field :status_code, Integer

      field :raw_response, T.nilable(Faraday::Response)
      # Successful authentication.
      field :token, T.nilable(Operations::OpenIdConnectAuthToken)


      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response), token: T.nilable(Operations::OpenIdConnectAuthToken)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil, token: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
        @token = token
      end
    end
  end
end
