// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Shared {
    /// An int32 enum property.
    public enum SimpleObjectWithTypeInt32Enum: Int, Codable, APIValue {
        case fiftyFive = 55
        case sixtyNine = 69
        case oneHundredAndEightyOne = 181
    }}
