"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from openapi.models.shared import errortype as shared_errortype
from openapi.types import BaseModel
from typing import Optional

class ErrorData(BaseModel):
    code: Optional[str] = None
    message: Optional[str] = None
    type: Optional[shared_errortype.ErrorType] = None
    


class Error(Exception):
    data: ErrorData

    def __init__(self, data: ErrorData):
        self.data = data

    def __str__(self) -> str:
        return self.data.message if self.data.message is not None else "unknown error"

