// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package tests

import (
	"context"
	"net/http"
	"testing"

	sdk "openapi/v3"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGlobalSecurityFlattening(t *testing.T) {
	recordTest("auth-global-security-flattening")

	s := sdk.New(sdk.WithSecurity("Bearer testToken"))

	res, err := s.Auth.APIKeyAuthGlobal(context.Background())
	require.NoError(t, err)
	require.NotNil(t, res)
	assert.Equal(t, http.StatusOK, res.StatusCode)
	assert.True(t, res.Token.Authenticated)
	assert.Equal(t, "testToken", res.Token.Token)
}
