
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Operations
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    
    public class HeaderParamsMapHeaders
    {

        [JsonProperty("X-Header-Map")]
        public string XHeaderMap { get; set; } = default!;

        [JsonProperty("X-Header-Map-Explode")]
        public string XHeaderMapExplode { get; set; } = default!;
    }
}