//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Operations
{
    using Newtonsoft.Json;
    using Openapi.Models.Operations;
    using Openapi.Utils;
    
    /// <summary>
    /// A response body that contains the simpleObject sent in the request body
    /// </summary>
    public class UsageExamplePostResponseBody
    {

        [JsonProperty("json", NullValueHandling = NullValueHandling.Include)]
        public UsageExamplePostJson? Json { get; set; }
    }
}