/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statusCodeStatusCode2XX } from "../funcs/statusCodeStatusCode2XX.js";
import { statusCodeStatusCode4XX } from "../funcs/statusCodeStatusCode4XX.js";
import { statusCodeStatusCode5XX } from "../funcs/statusCodeStatusCode5XX.js";
import { statusCodeStatusCodeDefault } from "../funcs/statusCodeStatusCodeDefault.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "./types/fp.js";

export class StatusCode extends ClientSDK {
  async statusCode2XX(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(statusCodeStatusCode2XX(
      this,
      options,
    ));
  }

  async statusCode4XX(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(statusCodeStatusCode4XX(
      this,
      options,
    ));
  }

  async statusCode5XX(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(statusCodeStatusCode5XX(
      this,
      options,
    ));
  }

  async statusCodeDefault(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(statusCodeStatusCodeDefault(
      this,
      options,
    ));
  }
}
